[package]
name = "spl-compiler"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
spl-lexer.workspace = true
spl-diagnostic.workspace = true
spl-syntax.workspace = true
spl-parser.workspace = true
spl-ast.workspace = true
spl-sema.workspace = true
spl-hir.workspace = true
spl-mir.workspace = true
spl-codegen.workspace = true
spl-package.workspace = true
ariadne.workspace = true
la-arena.workspace = true
lasso.workspace = true
logos.workspace = true
rowan.workspace = true
rustc-hash.workspace = true

# Stdlib embedding at compile time
include_dir.workspace = true

# Error handling
thiserror.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
expect-test.workspace = true
proptest.workspace = true
